### ISSUE TITLE
discrepancy between the colors of the theme and the screenshoots

### ISSUE THREAD

**Issue by vinniec** [tamimmirza/Darker-Than-Black#1]
Hey, today I tried a few themes but in the end I decided to stop with yours because everyone else had too many colors and I was confused.

I'm writing you this post however to warn you that the colors in the screenshoots you provided are different from those of the theme.
If I understand correctly the theme installed has this configuration:
green: comments
white: variables name (except class definitions)
blue: reserved keywords and operators, parameters, values (and keyword-argument with the full name of the argument)
Ligh blue: class names in the definition, special characters backquoted inside strings
Light blue very clear: Builtin types
Violet: for the keyword self and for the truncation of the lines with '\'

I noticed these differences whit the screenshoot:
Violet: for strings
White for the dots (.)
Blue for placeolders {} inside strings.

I still have to understand some logics of your groupings, but your theme relaxes me more than others, I hope that any eventual changes you make do not make it too much like a rainbow :)

**Comment by tamimmirza** [comment]
Yes, I had forgotten to update the repo with proper screenshots. It has been fixed now.

Thank you for liking my theme.
As for the logic behind the groupings it is preset by VS Code's extension tool so the best I could do is play with the colors.
